# Generated by Django 5.2.5 on 2026-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_memoryasset_index_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='mode',
            field=models.CharField(choices=[('memorial', '回憶連結'), ('fictional', '幻想伙伴'), ('archive', '回憶整理')], max_length=16),
        ),
    ]
