# Generated by Django 5.2.5 on 2026-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_character_archive_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='language',
            field=models.CharField(choices=[('zh-HK', '廣東話'), ('en', 'English')], default='zh-HK', max_length=8),
        ),
    ]
