# Generated by Django 5.2.5 on 2026-10-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_character_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
