# Generated by Django 5.2.5 on 2026-10-05 04:11

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_memoryasset_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('dedication', models.TextField(blank=True)),
                ('excluded', models.JSONField(blank=True, default=list)),
                ('pdf', models.FileField(blank=True, upload_to=api.models.book_pdf_path)),
                ('export_status', models.CharField(choices=[('none', '未匯出'), ('pending', '整理緊'), ('ready', '完成'), ('failed', '失敗')], default='none', max_length=16)),
                ('export_error', models.CharField(blank=True, max_length=200)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='api.character')),
            ],
        ),
    ]
